### PR TITLE
M131 public py3.13 2nd try

### LINKED ISSUE #230: deprecation of `distutils`upstream for python >= 3.12
Been getting this warning when I do local builds (`python setup.py ...`) for a while now:

```
skia-python/setup.py:8: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 


  from numpy.distutils.ccompiler import CCompiler_compile
/usr/lib/python3.12/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
WARNING: The wheel package is not available.
```

Nothing urgent yet, but possibly needs some work for python 3.13.

### PR DESCRIPTION
**Pull request by HinTak**
Tidied up from #273 . Includes #272 (and #267 )

There is only one commit beyond #272 - it splits the cibuildwheel job into two, one for 3.10 to 3.13, another for 3.8 and 3.9. Wastes CPU time by building skia unnecessarily 4 times I think, but this is marginally faster than the current 3.8 to 3.12 build, because there is more parallelism as we do 3.8/3.9 vs 3.10-3.13 in parallel.

Fixes #230 for the near future, I think.

### CODE REVIEW

**Comment by theacodes** [comment]
Hi 👋🏻 , I'm a downstream user of `skia-python` that's eager to upgrade to Python 3.13. Is there anything I can do to help this along? I'm happy to test it out, review the PR, or just offer encouragement. 😄

**Comment by HinTak** [comment]
@theacodes thanks for the offer. There is nothing needed on this pull itself: we basically release the next skia-python when the next upstream skia comes out. That should be in about a week or two; so you just need to wait about two weeks max. This will likely be merged with #274, which has a lot more exciting new stuff in. Give that a try - you can download pre-built wheels from https://github.com/kyamagu/skia-python/actions for either this pull or #274 , if you want to test out either the vanilla python 3.13 builds, or the SKRuntimeEffect binding builds (still with 3.12). Lastly, you can always buy me a coffee under the sponsor/donate link on my profile.

Btw, this will merge with #274 first, and #274 being the main merge, for the next release.

**Comment by theacodes** [comment]
Thank you! I'll give things a try and let you know if I run into issues. Appreciate all your work!

**Comment by HinTak** [comment]
@theacodes from the other stuff you do, it looks like you might be interested the new runtime effect functionality - I only have a few static examples, but I think it should be possible to do animated graphics effect with it. Like a pulsating heart or rippling water/waves, or something. Get some inspiration from some of the opengl shader demos on youtube and port them to skia SKSL for some visual effect, if that intetests you.

**Comment by m4rc1e** [comment]
Thank you very much for your work on this HinTak! LGTM.

**Pull request merged**
