### PR TITLE
M126 public

### PR DESCRIPTION
**Pull request by HinTak**
There is no change other than moving skia forward. (Overloading SkCanvas::drawArc was included in the m125 pull since it is harmless).

### CODE REVIEW

**Comment by HinTak** [comment]
No user-visible change between m125 and m126
(SkCanvas::drawArc overloaded; Not adding SkArc class yet)

New to m125:

* Metal-enabled on Mac OS, and added Metal APIs equivalents to Vulkan's.

Changes since m124:

* Dropping Python 3.7 support

* GrContext_Base.defaultBackendFormat and GrContext_Base.compressedBackendFormat
   re-enabled (disabled between m87 and m116)

* Corrected two typos in Vulkan code

* MemoryStream.asData and MemoryStream.skipToAlign4 now emulated
  (changed/removed upstream)


@kyamagu there is no user-visible change between m125 and m126, so I thought a 126 beta might as well go out, instead of a 125 beta.

**Comment by HinTak** [comment]
This differs from #244 by only the additions of release notes and a comment. (Plus change in skia and versioning)

**Review by kyamagu — APPROVED** [review]

**Comment by kyamagu** [comment]
Thanks, LGTM

**Comment by HinTak** [comment]
2091 passed, 98 skipped, 11 xfailed, 27 warnings

**Pull request merged**
