### PR TITLE
M119 public

### PR DESCRIPTION
**Pull request by HinTak**
This is inclusive of everything in #204 . Let's see if we can fix a few more of the skips before m120 is out, before merging.

### CODE REVIEW

**Comment by HinTak** [comment]
@kyamagu #204 added another 19 skips, this 4 more at the moment. So hope to get skip number lowered and passed number higher before another release. However there is probably a good reason for a reason if somebody needs/wants a python 3.12 build.

**Review by kyamagu — APPROVED** [review]
LGTM!

**Comment by kyamagu** [comment]
@HinTak Thanks! Go ahead to make a beta release

**Comment by HinTak** [comment]
@kyamagu m120 is out today, so I'd like to release this - with one more change: bump it up to 119b4 (since the last one was 117b3). The number of passed tests is marginally lower than 117b3, as a few things were withdrawn/removed upstream, but at least I got #209 fixed so nothing too common / major is broken AFAIC. I'll probably continue with future upstream skia, but would suggest not to merge (e.g. m118) if it is purely disabling more api's.

The #155 related change is more about **avoid** segfault, not actually fixing the reported problem yet - so that commit message is mis-worded. Sorry about that.

I'll bump it up to 119b4 when the current CI finishes, then merge, then release, unless you say otherwise.

**Comment by kyamagu** [comment]
@HinTak Thanks for the hard work! Yes, you can go ahead with the 119b4 release (or, perhaps rename it to 119b1 to reset the minor number).

**Pull request merged**
