### PR TITLE
Icudtl.dat fix

### LINKED ISSUE #268: Skparagraph on windows, and icudtl.dat
The icu module fails to load - looking online it seems to be a generic problem across skia on windows, with rust , c/c++, and java:

https://github.com/rust-skia/rust-skia/blob/master/skia-safe/README.md#embed-icudtl-enabled-by-default

https://groups.google.com/g/skia-discuss/c/FpL3Q0XK8Ag

https://stackoverflow.com/questions/60048968/build-errors-with-ninja-and-skia-unable-to-find-icudtl-dat-even-though-the-file

### PR DESCRIPTION
**Pull request by HinTak**
Download icudtl.dat in CI, re-enable tests and update README.m130.

Fixes #268

### CODE REVIEW

**Comment by HinTak** [comment]
The CI error is

```
File "<string>", line 1
      'import
            ^
  SyntaxError: EOL while scanning string literal
```

It is either all the quotes and double quotes, or the length. Probably need to put it in a shell script.

**Comment by HinTak** [comment]
Okay, venv is significantly different from just plain running "import skia; ...".

And it is failing ob something that used to pass:

```
================================== FAILURES ===================================
  ____________________________ test_svg_blob_bounds _____________________________
  
  svg_blob = None
  
      def test_svg_blob_bounds(svg_blob):
  >       bounds = svg_blob.bounds()
  E       AttributeError: 'NoneType' object has no attribute 'bounds'
  
  D:\a\skia-python\skia-python\tests\test_font.py:255: AttributeError
  ---------------------------- Captured stderr setup ----------------------------
  SkIcuLoader: datafile missing: C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.8.10\tools\icudtl.dat.
  _____________________ test_fontmgr_custom_svg_blob_bounds _____________________
  
  svgfont_path = 'D:\\a\\skia-python\\skia-python\\skia\\resources\\fonts\\SampleSVG.ttf'
  
      def test_fontmgr_custom_svg_blob_bounds(svgfont_path):
          svgface = skia.FontMgr.New_Custom_Empty().makeFromFile(svgfont_path)
          text = "abcdefgh"
          font = skia.Font(svgface,109)
          svg_blob = skia.TextBlob.MakeFromShapedText(text, font)
  >       bounds = svg_blob.bounds()
  E       AttributeError: 'NoneType' object has no attribute 'bounds'
  
  D:\a\skia-python\skia-python\tests\test_font.py:270: AttributeError
  ============================== warnings summary ===============================
```

**Comment by HinTak** [comment]
Filed the shaper failure upstream: https://issues.skia.org/371224771

**Comment by HinTak** [comment]
Started a discussion over at rust-skia https://github.com/rust-skia/rust-skia/discussions/1041

**Comment by HinTak** [comment]
So the presence of the file on windows breaks shaping. If it is absent, you get a warning (and likely something else does not work)

**Comment by MeetWq** [comment]
use
```
import sys
print(sys.base_prefix)
```
to get python path?

https://stackoverflow.com/questions/54641473/get-path-to-original-python-executable-not-the-virtualenv

**Comment by HinTak** [comment]
Superceded by #279

**Pull request closed without merging**
