### PR TITLE
M124 public

### PR DESCRIPTION
**Pull request by HinTak**
@kyamagu nothing too exciting compared to m123 - the vulkan initialization changed - from `instance = class() ; instance.initVulkan()` to `instance = class.MakeVk()`. So tests need to change - I chose to mark the old test as skip and add a new test, rather than replace, since the calling is quite different.

This includes the fix to #235 so needs reviewing in the next few weeks when you get around to it (before m125). Includes the other pulls.

I think there was a earlier MakeGL that I missed. ( I just commented out the initGL). M124 release notes mention a similar MakeMetal() change too.

### CODE REVIEW

**Comment by HinTak** [comment]
I also don't quite get the `reinterprete_cast` before/after this https://github.com/kyamagu/skia-python/pull/236/commits/3ca9d20e57c06e7071bb054ab2dd7adc9fed7ef7 - the vulkan pointer seems to be quite strange and not template'able.

**Comment by HinTak** [comment]
The vulkan header situation is a mess - within skia, there is one under `third_party/externals/vulkan-headers/include`, another under `include/third_party/vulkan`, and also, on Linux, under `/usr/include`.

I started using the `third_party/externals` one since we started using the freetype ones there too. But if seems that internally skia switches between the other two (system or private under `include/third_party`).

**Comment by kyamagu** [comment]
I'm not familiar with Vulkan API, but it could be that there are platform-dependent headers located in different places.

**Comment by HinTak** [comment]
Yes, that's true about platform-dependent headers. But the situation is a bit complicated in skia - there can be up to 3 (complete AFAIK) sets of headers in a linux build - one in third_party/externals, one in include/third_party (I believe they are synced periodically, one is a submodule from another repo, the other is committed in tree), and also from /usr/include. There are also defines for different behaviour depending on whether it is in skia (building skia itself) vs skia clients (external code that uses skia). For the latter, they seem to have defines to prefer /usr/include.

It is where the last part skia-python is having trouble with - skia-python is strictly-speaking a client, but does go quite deep within skia.

Anyway, this area (and also hardware-accelerated backend of graphics-related code) seems to be getting a fair bit of attention lately. The Metal code has substantially changed (which we don't use), and the GL code had changed a month or so ago (I think I just commented out some code to get it to build, need to revisit).

**Comment by HinTak** [comment]
@kyamagu I added readme m121 to 124, and also updated m116, so those give a summary of changes. SampleOptions() and paint.getblendmode() are new work on issues, in addition to just updating the upstream skia. Ready for review for another public beta.

Upstream m125 was out about a week ago.

**Comment by HinTak** [comment]
@kyamagu ping on review? M125 is out, small adjustments in skpath, changes in MemoryStream looks slightly complicated, and libunicode has split into _core and _icu and it seems we needs both; and it seems to require the internal copy of libicu (and doesn't work with my system-wide one). M125 looks a bit troublesome.

**Review by kyamagu — APPROVED** [review]
Thanks!

**Comment by HinTak** [comment]
Latest:

2091 passed, 98 skipped, 11 xfailed, 27 warnings

**Pull request merged**
